"""Add calories column to food table

Revision ID: a01ce106a9a6
Revises: 304e0023735b
Create Date: 2023-05-25 16:57:41.549489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01ce106a9a6'
down_revision = '304e0023735b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories', sa.Float(), nullable=True))
        op.add_column('food', sa.Column('calories', sa.Float))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food', schema=None) as batch_op:
        batch_op.drop_column('calories')

    # ### end Alembic commands ###
